export {
  faChevronRight,
  faChevronDown,
  faBars,
  faSearch,
  faCheck,
  faSliders,
  faBookmark,
  faBuildingUser,
  faFolderOpen,
  faUsers,
  faFileLines,
  faFileVideo,
  faFileZipper,
  faUserGear,
  faCircleUser,
  faPen,
  faTrashAlt,
  faSort,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faSpinner,
  faTags,
  faArrowRightFromBracket,
  faArrowRightToBracket,
} from '@fortawesome/free-solid-svg-icons';

export {
  faCopyright,
  faBookmark as farBookmark,
} from '@fortawesome/free-regular-svg-icons';
