export {
  faChevronRight,
  faChevronDown,
  faBars,
  faSearch,
  faCheck,
  faSliders,
  faBookmark,
  faBuildingUser,
  faFolderOpen,
  faUsers,
  faFileLines,
  faFileVideo,
  faFileZipper,
  faUserGear,
  faCircleUser,
  faPen,
  faTrashAlt,
  faSort,
} from '@fortawesome/free-solid-svg-icons';
